/*
 * Copyright (C) 2007 Erik Swenson - erik@oreports.com
 * 
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc., 59 Temple
 * Place - Suite 330, Boston, MA 02111-1307, USA.
 *  
 */
package org.efs.openreports.services.output;

import org.efs.openreports.ReportConstants;
import org.efs.openreports.ReportConstants.Status;

/**
 * Contains the data returned by request to generate a report. Content attributes are optional and usually only returned for synchronous requests.
 * @see  ReportConstants
 */

public class ReportServiceOutput 
{       
    /**
	 * content generated by the service
	 * @uml.property  name="content"
	 */
    private byte[] content; 
    
    /**
	 * mime type of the content
	 * @uml.property  name="contentType"
	 */
    private String contentType;    
    
    /**
	 * file extension of the content
	 * @uml.property  name="contentExtension"
	 */
    private String contentExtension;
    
    /**
	 * message returned by the request
	 * @uml.property  name="contentMessage"
	 */
    private String contentMessage;   
    
    /**
	 * status of the request
	 * @uml.property  name="status"
	 * @uml.associationEnd  
	 */
    private Status status;

    /**
	 * @return
	 * @uml.property  name="content"
	 */
    public byte[] getContent() 
    {
        return content;
    }
    
    /**
	 * @param content
	 * @uml.property  name="content"
	 */
    public void setContent(byte[] content) 
    {
        this.content = content;
    }
    
    /**
	 * @return
	 * @uml.property  name="contentMessage"
	 */
    public String getContentMessage() 
    {
        return contentMessage;
    }
    
    /**
	 * @param contentMessage
	 * @uml.property  name="contentMessage"
	 */
    public void setContentMessage(String contentMessage) 
    {
        this.contentMessage = contentMessage;
    }
    
    /**
	 * @return
	 * @uml.property  name="contentType"
	 */
    public String getContentType() 
    {
        return contentType;
    }
    
    /**
	 * @param contentType
	 * @uml.property  name="contentType"
	 */
    public void setContentType(String contentType) 
    {
        this.contentType = contentType;
    }
    
    /**
	 * @return
	 * @uml.property  name="contentExtension"
	 */
    public String getContentExtension() 
    {
        return contentExtension;
    }
    
    /**
	 * @param contentExtension
	 * @uml.property  name="contentExtension"
	 */
    public void setContentExtension(String contentExtension) 
    {
        this.contentExtension = contentExtension;
    }  
    
    /**
	 * @return
	 * @uml.property  name="status"
	 */
    public Status getStatus()
    {
		return status;
	}

	/**
	 * @param status
	 * @uml.property  name="status"
	 */
	public void setStatus(Status status) 
	{
		this.status = status;
	}    
}
