package https.ets_org.edm.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-10-15T07:01:18.910-04:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "https://ets.org/edm/webservices/", name = "ScoreReportsServices.Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface ScoreReportsServicesSoap {

    @WebResult(name = "GetHistoryReportResult", targetNamespace = "https://ets.org/edm/webservices/")
    @RequestWrapper(localName = "GetHistoryReport", targetNamespace = "https://ets.org/edm/webservices/", className = "https.ets_org.edm.webservices.GetHistoryReport")
    @WebMethod(operationName = "GetHistoryReport", action = "https://ets.org/edm/webservices/GetHistoryReport")
    @ResponseWrapper(localName = "GetHistoryReportResponse", targetNamespace = "https://ets.org/edm/webservices/", className = "https.ets_org.edm.webservices.GetHistoryReportResponse")
    public byte[] getHistoryReport(
        @WebParam(name = "clientUserId", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String clientUserId,
        @WebParam(name = "clientPassword", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String clientPassword,
        @WebParam(name = "year", targetNamespace = "https://ets.org/edm/webservices/")
        int year
    );

    @WebResult(name = "GetNewScoreReportsResult", targetNamespace = "https://ets.org/edm/webservices/")
    @RequestWrapper(localName = "GetNewScoreReports", targetNamespace = "https://ets.org/edm/webservices/", className = "https.ets_org.edm.webservices.GetNewScoreReports")
    @WebMethod(operationName = "GetNewScoreReports", action = "https://ets.org/edm/webservices/GetNewScoreReports")
    @ResponseWrapper(localName = "GetNewScoreReportsResponse", targetNamespace = "https://ets.org/edm/webservices/", className = "https.ets_org.edm.webservices.GetNewScoreReportsResponse")
    public byte[] getNewScoreReports(
        @WebParam(name = "clientUserId", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String clientUserId,
        @WebParam(name = "clientPassword", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String clientPassword,
        @WebParam(name = "strSubProgram", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String strSubProgram
    );

    @WebResult(name = "GetReportingDatesResult", targetNamespace = "https://ets.org/edm/webservices/")
    @RequestWrapper(localName = "GetReportingDates", targetNamespace = "https://ets.org/edm/webservices/", className = "https.ets_org.edm.webservices.GetReportingDates")
    @WebMethod(operationName = "GetReportingDates", action = "https://ets.org/edm/webservices/GetReportingDates")
    @ResponseWrapper(localName = "GetReportingDatesResponse", targetNamespace = "https://ets.org/edm/webservices/", className = "https.ets_org.edm.webservices.GetReportingDatesResponse")
    public byte[] getReportingDates(
        @WebParam(name = "clientUserId", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String clientUserId,
        @WebParam(name = "clientPassword", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String clientPassword
    );

    @WebResult(name = "GetScoreReportsInCDScoreLinkFormatResult", targetNamespace = "https://ets.org/edm/webservices/")
    @RequestWrapper(localName = "GetScoreReportsInCDScoreLinkFormat", targetNamespace = "https://ets.org/edm/webservices/", className = "https.ets_org.edm.webservices.GetScoreReportsInCDScoreLinkFormat")
    @WebMethod(operationName = "GetScoreReportsInCDScoreLinkFormat", action = "https://ets.org/edm/webservices/GetScoreReportsInCDScoreLinkFormat")
    @ResponseWrapper(localName = "GetScoreReportsInCDScoreLinkFormatResponse", targetNamespace = "https://ets.org/edm/webservices/", className = "https.ets_org.edm.webservices.GetScoreReportsInCDScoreLinkFormatResponse")
    public byte[] getScoreReportsInCDScoreLinkFormat(
        @WebParam(name = "clientUserId", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String clientUserId,
        @WebParam(name = "clientPassword", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String clientPassword,
        @WebParam(name = "reportDate", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String reportDate,
        @WebParam(name = "strSubProgram", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String strSubProgram
    );

    @WebResult(name = "GetScoreReportsGivenReportingDateResult", targetNamespace = "https://ets.org/edm/webservices/")
    @RequestWrapper(localName = "GetScoreReportsGivenReportingDate", targetNamespace = "https://ets.org/edm/webservices/", className = "https.ets_org.edm.webservices.GetScoreReportsGivenReportingDate")
    @WebMethod(operationName = "GetScoreReportsGivenReportingDate", action = "https://ets.org/edm/webservices/GetScoreReportsGivenReportingDate")
    @ResponseWrapper(localName = "GetScoreReportsGivenReportingDateResponse", targetNamespace = "https://ets.org/edm/webservices/", className = "https.ets_org.edm.webservices.GetScoreReportsGivenReportingDateResponse")
    public byte[] getScoreReportsGivenReportingDate(
        @WebParam(name = "clientUserId", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String clientUserId,
        @WebParam(name = "clientPassword", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String clientPassword,
        @WebParam(name = "reportDate", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String reportDate,
        @WebParam(name = "strSubProgram", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String strSubProgram
    );

    @WebResult(name = "GetHistoryReportGivenCandidateResult", targetNamespace = "https://ets.org/edm/webservices/")
    @RequestWrapper(localName = "GetHistoryReportGivenCandidate", targetNamespace = "https://ets.org/edm/webservices/", className = "https.ets_org.edm.webservices.GetHistoryReportGivenCandidate")
    @WebMethod(operationName = "GetHistoryReportGivenCandidate", action = "https://ets.org/edm/webservices/GetHistoryReportGivenCandidate")
    @ResponseWrapper(localName = "GetHistoryReportGivenCandidateResponse", targetNamespace = "https://ets.org/edm/webservices/", className = "https.ets_org.edm.webservices.GetHistoryReportGivenCandidateResponse")
    public byte[] getHistoryReportGivenCandidate(
        @WebParam(name = "clientUserId", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String clientUserId,
        @WebParam(name = "clientPassword", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String clientPassword,
        @WebParam(name = "year", targetNamespace = "https://ets.org/edm/webservices/")
        int year,
        @WebParam(name = "candidateId", targetNamespace = "https://ets.org/edm/webservices/")
        java.lang.String candidateId
    );
}
